version: '3.7'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - "./data/mongo/db:/data/db"
  api:
    build:
      context: ./
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - mongo
